apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmapgen-deployment
  labels:
    app: mindmapgen
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: mindmapgen
  template:
    metadata:
      labels:
        app: mindmapgen
    spec:
      containers:
      - name: mindmapgen
        # !!! IMPORTANT: Replace with your actual image name and tag !!!
        image: your-dockerhub-username/mindmapgen:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always # Or IfNotPresent if preferred

---

apiVersion: v1
kind: Service
metadata:
  name: mindmapgen-service
spec:
  type: NodePort
  selector:
    app: mindmapgen # Must match the labels on the pods
  ports:
    - protocol: TCP
      port: 80       # Port inside the cluster for the service
      targetPort: 8080 # Port on the container
      # nodePort: 30080 # Optional: specify a NodePort, otherwise K8s chooses one > 30000
      # If you uncomment nodePort, ensure 30080 is available on your nodes. 