name: "Default Theme"
style: "standard"
colors:
  background: "#FFFFFF"
  connectionLine: "#0D0B22"
nodeStyles:
  root:
    fillColor: [0.051, 0.043, 0.133]
    strokeColor: [0.051, 0.043, 0.133]
    textColor: [1.0, 1.0, 1.0]
  level1:
    fillColor: [0.96, 0.97, 0.98]
    strokeColor: [0.85, 0.86, 0.88]
    textColor: [0.0, 0.0, 0.0]
  level2:
    fillColor: [0.96, 0.97, 0.98]
    strokeColor: [0.85, 0.86, 0.88]
    textColor: [0.0, 0.0, 0.0]
  leaf:
    fillColor: [1.0, 1.0, 1.0]
    strokeColor: [0.90, 0.91, 0.93]
    textColor: [0.0, 0.0, 0.0]
layout:
  minNodeWidth: 110.0
  maxNodeWidth: 250.0
  minNodeHeight: 36.0
  levelSpacing: 110.0
  nodeSpacing: 20.0
  cornerRadius: 10.0
  fontSize: 18.0
  scale: 3.0
  lineHeight: 24.0
  textPadding: 18.0 